Import('env', 'rtech1')
import scons.utils

use = env.Clone()
try:
    utils.safeParseConfig(use, 'pkg-config r-tech1 --libs --cflags')
except:
    use['LIBS'].append(rtech1)
    use['LIBS'].append(env['LIBS'])
    pass
init_test = use.Program('init-test', 'main.cpp')

Return('init_test')
