Import('env', 'rtech1')

use = env.Clone()
use['LIBS'].append(rtech1)
use['LIBS'].append(env['LIBS'])
use.ParseConfig('pkg-config zlib --libs --cflags')

init_test = use.Program('init-test', 'main.cpp')

Return('init_test')
