Import('env')

import helpers
import os.path
modules = helpers.read_cmake_list(os.path.join(helpers.findDirectory('src/util'), 'CMakeLists.txt'))

source = []
for module in modules:
    source.append(modules[module])

x = env.StaticLibrary('paintown-util', source)
Return('x')
