import os
Import( 'env' )

# env = Environment( ENV = os.environ )

source = Split("""
src/crc.cpp
src/err.cpp
src/errorstr.cpp
src/group.cpp
src/hthread.cpp
src/htcondition.cpp
src/ipx.cpp
src/loopback.cpp
src/htmutex.cpp
src/nl.cpp
src/nltime.cpp
src/sock.cpp
""");

# env.Append(CPPPATH = 'hawknl')

x = env.StaticLibrary('hawknl', source)
Return('x')
